FROM php:7.2-apache
##FROM php:7.2-fpm

MAINTAINER tiochan <tiochan@gmail.com>

RUN apt-get update && \
 apt-get install -y --no-install-recommends \
 libpng-dev

WORKDIR /var/www/html/sifit/
RUN docker-php-ext-install mysqli gd

ADD sifit.tgz /var/www/html/
EXPOSE 80

### CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

ENV MYSQL_END_POINT="127.0.0.1"
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_ROOT_USER=root

RUN sed -i "s#localhost#${MYSQL_END_POINT}#g" /var/www/html/sifit/conf/app.conf.php
RUN sed -i "s#DEVELOPMENT\",true#DEVELOPMENT\",false#g" /var/www/html/sifit/conf/app.conf.php
RUN sed -i "s#DEBUG\",true#DEBUG\",false#g" /var/www/html/sifit/conf/app.conf.php


